# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Repostat for Windows 2019

on:
  pull_request:
    branches: [ master, v2.0.x ]

jobs:
  windows_build:

    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Install repostat into virtual environment
      run: |
        python -m pip install .

    - name: Run repostat
      run: |
        repostat . ./output --no-browser --contribution

    - name: Check generated report integrity
      run: python tools/check_report_files.py ./output
